version: '3.3'

services:
  nextjs:
    ports:
      - 3000:3000
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app/shareit/
      - /usr/src/app/shareit/node_modules
      - /usr/src/app/shareit/.next